(custom-set-faces
 '(cfw:face-title ((t (:foreground "#D7D0C7" :weight bold :height 2.0 :inherit variable-pitch))))
 '(cfw:face-header ((t (:foreground "#D7D0C7" :weight bold))))
 '(cfw:face-sunday ((t :foreground "#D7D0C7" :background "#151515" :weight bold)))
 '(cfw:face-saturday ((t :foreground "#D7D0C7" :background "#151515" :weight bold)))
 '(cfw:face-holiday ((t :background "#151515" :foreground "#B8D68C" :weight bold)))
 '(cfw:face-grid ((t :foreground "DarkGrey")))
 '(cfw:face-default-content ((t :foreground "#D7D0C7")))
 '(cfw:face-periods ((t :foreground "cyan")))
 '(cfw:face-day-title ((t :background "#333333")))
 '(cfw:face-default-day ((t :weight bold :inherit cfw:face-day-title)))
 '(cfw:face-annotation ((t :foreground "RosyBrown" :inherit cfw:face-day-title)))
 '(cfw:face-disable ((t :foreground "DarkGray" :inherit cfw:face-day-title)))
 '(cfw:face-today-title ((t :background "#E84F4F" :weight bold)))
 '(cfw:face-today ((t :background: "333333" :weight bold)))
 '(cfw:face-select ((t :background "#B8D68C")))
 '(cfw:face-toolbar ((t :foreground "#D7D0C7" :background "#151515")))
 '(cfw:face-toolbar-button-off ((t :foreground "#D7D0C7" :weight bold)))
 '(cfw:face-toolbar-button-on ((t :foreground "#D7D0C7" :weight bold))))

