#!/bin/zsh
c=$( netstat --tcp --numeric | awk 'NR>2 {print $5}'| sort -n -t : -k 2,2 | uniq | wc -l)
d=$( echo $c )
if [ "$d" -lt "23" ] && [ "$d" -gt "0" ]; then

echo "Domains / Nameservers"

x=$( netstat --tcp --numeric | awk 'NR>2 {print $5}'| sort -n -t : -k 2,2 | uniq ) 
y=$( netstat --tcp --numeric | awk 'NR>2 {print $5}'| sort -n -t : -k 2,2 | uniq | sed -e 's/\:.*//' ) 



a=$( for i in $y; do
dig @8.8.8.8 -x $i +short | sed 's/[.]$//g'
done )

b=$( for i in $x; do
dig @8.8.8.8 -x $i | grep -e "SOA" -e "PTR" | awk '{print $5}' | grep "." | sed 's/[.]$//g'
done )

echo -e "$a \n$b" | grep "." | cut -c 1-21 | sort | uniq
echo " "
fi

exit