#!/bin/zsh
# dmenu wrapper, assing some options
# if they weren't given.
#
# TODO: integrate with monsterwm,
# maybe make monsterwm output some of it's
# settings as enviroiment variables?
main() {
   local ARGS=
      local FONT=
         [[ "$@" != *-fn ]] && FONT="uushi 8"
            [[ "$@" != *-nb ]] && ARGS="$ARGS -nb #151515"
               [[ "$@" != *-nf ]] && ARGS="$ARGS -nf #EBEBEB"
                  [[ "$@" != *-sb ]] && ARGS="$ARGS -sb #9DBA3A"
                     [[ "$@" != *-sf ]] && ARGS="$ARGS -sf #151515"
                        [[ -n "$FONT" ]] && {
                              /usr/bin/dmenu -b -fn "$FONT" $ARGS "$@"; return;
                                 } || { /usr/bin/dmenu $ARGS "$@"; return; }
                                 }
                                 main "$@"
