#!/bin/zsh

lsof -nPi | awk '/.*python[2]*/ || /.*java/ {cmd[$2] = $2;next}
                 !/COMMAND/ {cmd[$1]=$1}
                 END {for (item in cmd ) {
                          sub(".*/", "", item)
                         print item}
                     }'

