#!/bin/zsh
# expects a line from monsterwm's output as argument ("$1")
# prints formatted output to be used as input for bar
# reference: bar by LemonBoy -- https://github.com/LemonBoy/bar

# desktop status
for desk; do
m="${desk%%:*}" desk="${desk#*:}" # monitor id
    n="${desk%%:*}" desk="${desk#*:}" # is current monitor
        d="${desk%%:*}" desk="${desk#*:}" # desktop id
            w="${desk%%:*}" desk="${desk#*:}" # window count
                l="${desk%%:*}" desk="${desk#*:}" # layout mode
                    c="${desk%%:*}" desk="${desk#*:}" # is current desktop
                        u="${desk%%|*}" desk="${desk#*|}" # has urgent hint
                            t="${desk#0}" # finally the title


                                # desktop id
                                    case "$d" in
                                            0) d=" main" ;; 1) d=" code" ;;
                                                    2) d=" misc" ;;
                                                        esac

                                                            # current desktop on active monitor
                                                                if [ $n -ne 0 -a $c -ne 0 ]
                                                                    then bg="\b9" un="\u3"
                                                                            case "$l" in
                                                                                        0) s="Classic Tiling Mode" ;; 1) s="Monocle Mode" ;; 2) s="Bstack Mode" ;;
                                                                                                    3) s="Grid Mode" ;; 4) s="Bloat Mode" ;;
                                                                                                            esac && s="\u9\b9 $s \br\ur"
                                                                                                                # current desktop on inactive monitor
                                                                                                                    elif [ $c -ne 0 ]
                                                                                                                        then bg="\b9" un="\u9"
                                                                                                                            fi

                                                                                                                                # has urgent hint or no windows
                                                                                                                                    [ $u -ne 0 ] && un="\u3"
                                                                                                                                        [ $w -eq 0 ] && w="\f5-"

                                                                                                                                            if [ "$m" -eq 0 ]
                                                                                                                                                then mr="$mr$bg$fg$un $d \\f5[$w] \ur\br\fr"
                                                                                                                                                    fi

                                                                                                                                                    unset bg fg un
                                                                                                                                                    done

                                                                                                                                                    # music status
                                                                                                                                                    music="$(mpc current -f "%artist% - [%title%|%file%]")"
                                                                                                                                                    if [ -z "$music" ]; then music="nothing to see here" mstat=""
                                                                                                                                                    else
                                                                                                                                                    mstat="$(mpc | sed -rn '2s/\[([[:alpha:]]+)].*/\1/p')"
                                                                                                                                                        [ "$mstat" == "paused" ] && mstat="" || mstat=""
                                                                                                                                                        fi

                                                                                                                                                        # volume status
                                                                                                                                                        if [ "$(amixer get Master | sed -nr '$ s:.*\[(.+)]$:\1:p')" == "off" ]
                                                                                                                                                        then vol="[m]" vstat=""
                                                                                                                                                        else
                                                                                                                                                        vol="$(amixer get PCM | sed -nr '$ s:.*\[(.+%)].*:\1:p')"
                                                                                                                                                            if [ "${vol%\%}" -le 10 ]; then vstat=""
                                                                                                                                                                elif [ "${vol%\%}" -le 20 ]; then vstat=""; else vstat=""; fi
                                                                                                                                                                fi

                                                                                                                                                                # date and time
                                                                                                                                                                date="$(date +"%a %d %b %R")" dstat=""

                                                                                                                                                                printf '%s %s %s %s' "$mr" "$s" "\\b7\\u7\c $t \\br\ur" "\r"
                                                                                                                                                                printf ' \\u3\\b9 %s \\br\\ur %s' "$mstat" "$music" "$vstat" "$vol" "$dstat" "$date "
                                                                                                                                                                printf '\n'
