#!/bin/bash
while getopts d: opt; do
case "$opt" in
        d) mkdir -p "$OPTARG"; cd "$OPTARG" ;;
    esac
done
shift $((OPTIND - 1))
while [[ $1 ]]; do
notify-send -t 2000 "Fetching info: $1"
    title=$(youtube-dl -n -e "$1")
    if [[ $title ]]; then
notify-send -t 5000 "Downloading MP3: \"$title\""
        youtube-dl --max-quality 22 -R3 -tcn --extract-audio \
            --audio-format mp3 --audio-quality 192 "$1"
        notify-send -t 3000 "Download complete: \"$title\""
    else
notify-send -t 3000 "Can't find video at URL: $1"
    fi
shift
done